title:              "Hello world from Korea"
tagline:            "A blog that summarizes Korean issues and reactions"
email:              "hongtani625@gmail.com"
description:        "Korea is real good"
author:             "Hongtani"
baseurl:            ""
url:                "https://korealgood.com"
locale:             "ko_KR"
thumbnail:          "/img/thumbnail.jpeg"


# 블로그 disqus shortname
disqus:
  shortname: korealgood-com


# Social Profiles
twitter_username:   twitter_username
instagram_username: instagram_username
facebook_username:  facebook_username
linkedin_username:  linkedin_username

# Build settings
markdown:           kramdown
permalink:          /:title
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-paginate
